In [2]:
import numpy as np

In [3]:
type(np.array([1,2,3,4]))

numpy.ndarray

In [4]:
np.array([1,2,3,4,7.0])

array([1., 2., 3., 4., 7.])

In [6]:
np.array([1,2,3,4,7.0,'raj'])

array(['1', '2', '3', '4', '7.0', 'raj'], dtype='<U32')

In [45]:
arr = np.array([[1,2,3],[1,2,5],[1.21,45,7]], ndmin=5)

In [4]:
np.array([(1,2),(3,4)],dtype = complex)

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [40]:
a = np.array([(1,2),(3,4)],dtype = [('a','<i4'),('b','<i8')])

In [7]:
type(a[0][0])

numpy.int32

In [8]:
type(a[0][1])

numpy.int64

In [11]:
b = np.mat(a)

In [10]:
l = [1,3,5,8,9]
np.array(l)
np.asarray(l)
np.asanyarray(l)

array([1, 3, 5, 8, 9])

In [12]:
np.asanyarray(b)

matrix([[(1, 2), (3, 4)]], dtype=[('a', '<i4'), ('b', '<i8')])

In [13]:
np.asanyarray(l)

array([1, 3, 5, 8, 9])

In [14]:
issubclass(np.matrix, np.ndarray) #matrix is sub-class of nd array

True

In [20]:
c=a #shallow copy, array is mutable

In [21]:
d = np.copy(a) # deep copy

In [22]:
a[0][0] = 8

In [23]:
c

array([(8, 2), (3, 4)], dtype=[('a', '<i4'), ('b', '<i8')])

In [24]:
d

array([(8, 2), (3, 4)], dtype=[('a', '<i4'), ('b', '<i8')])

In [25]:
np.fromfunction(lambda i,j: i == j, (4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [26]:
np.fromfunction(lambda i,j: i/j, (4,4))

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_4696\4229925046.py:1: RuntimeWarning: divide by zero encountered in divide
  np.fromfunction(lambda i,j: i/j, (4,4))
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_4696\4229925046.py:1: RuntimeWarning: invalid value encountered in divide
  np.fromfunction(lambda i,j: i/j, (4,4))


array([[       nan, 0.        , 0.        , 0.        ],
       [       inf, 1.        , 0.5       , 0.33333333],
       [       inf, 2.        , 1.        , 0.66666667],
       [       inf, 3.        , 1.5       , 1.        ]])

In [27]:
def test(n):
    for i in range(n):
        yield i**3

In [28]:
test(30)

<generator object test at 0x0000023FF3F1B1D0>

In [30]:
for i in test(3):
    print(i)

0
1
8


In [31]:
gen = (i*i for i in range(5))

In [33]:
gen

<generator object <genexpr> at 0x0000023FFABC3100>

In [38]:
np.fromiter(gen, dtype = int)

array([], dtype=int32)

In [39]:
np.fromstring('1,3,4,5,5',sep=',',dtype=int)

array([1, 3, 4, 5, 5])

In [41]:
a.ndim

1

In [42]:
a.size

2

In [43]:
a.shape

(2,)

In [44]:
a.dtype

dtype([('a', '<i4'), ('b', '<i8')])

In [46]:
arr.shape

(1, 1, 1, 3, 3)

In [1]:
list(range(6.6))

TypeError: 'float' object cannot be interpreted as an integer

In [3]:
np.arange(6.6)

array([0., 1., 2., 3., 4., 5., 6.])

In [5]:
np.arange(9,6.6,-.3) #includes upper bond for float

array([9. , 8.7, 8.4, 8.1, 7.8, 7.5, 7.2, 6.9, 6.6])

In [6]:
np.arange(1,9,.2) #excludes upper bond for int

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. ,
       6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6,
       8.8])

In [7]:
np.linspace(1,9,10)

array([1.        , 1.88888889, 2.77777778, 3.66666667, 4.55555556,
       5.44444444, 6.33333333, 7.22222222, 8.11111111, 9.        ])

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros((2,5,4,3))

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [10]:
np.ones((3,4,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [11]:
np.empty((3,4))

array([[1.44032830e-311, 2.81617418e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.11260619e-306, 5.74084271e+169, 6.50957786e-091,
        3.76111729e+179],
       [8.31546613e-072, 8.44925200e+169, 6.48224660e+170,
        4.93432906e+257]])

In [13]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
np.linspace(2,4,4,endpoint=False,axis=0)

array([2. , 2.5, 3. , 3.5])

In [18]:
np.linspace([1,1],2,axis=0)

array([[1.        , 1.        ],
       [1.02040816, 1.02040816],
       [1.04081633, 1.04081633],
       [1.06122449, 1.06122449],
       [1.08163265, 1.08163265],
       [1.10204082, 1.10204082],
       [1.12244898, 1.12244898],
       [1.14285714, 1.14285714],
       [1.16326531, 1.16326531],
       [1.18367347, 1.18367347],
       [1.20408163, 1.20408163],
       [1.2244898 , 1.2244898 ],
       [1.24489796, 1.24489796],
       [1.26530612, 1.26530612],
       [1.28571429, 1.28571429],
       [1.30612245, 1.30612245],
       [1.32653061, 1.32653061],
       [1.34693878, 1.34693878],
       [1.36734694, 1.36734694],
       [1.3877551 , 1.3877551 ],
       [1.40816327, 1.40816327],
       [1.42857143, 1.42857143],
       [1.44897959, 1.44897959],
       [1.46938776, 1.46938776],
       [1.48979592, 1.48979592],
       [1.51020408, 1.51020408],
       [1.53061224, 1.53061224],
       [1.55102041, 1.55102041],
       [1.57142857, 1.57142857],
       [1.59183673, 1.59183673],
       [1.

In [19]:
np.logspace(2,3,5)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [23]:
d = np.linspace(1,40,10)

In [24]:
d

array([ 1.        ,  5.33333333,  9.66666667, 14.        , 18.33333333,
       22.66666667, 27.        , 31.33333333, 35.66666667, 40.        ])

In [25]:
d.reshape(10,1)

array([[ 1.        ],
       [ 5.33333333],
       [ 9.66666667],
       [14.        ],
       [18.33333333],
       [22.66666667],
       [27.        ],
       [31.33333333],
       [35.66666667],
       [40.        ]])

In [26]:
d.reshape(1,2,5)

array([[[ 1.        ,  5.33333333,  9.66666667, 14.        ,
         18.33333333],
        [22.66666667, 27.        , 31.33333333, 35.66666667,
         40.        ]]])

In [27]:
np.random.rand(3)

array([0.72860575, 0.20449724, 0.94927727])

In [28]:
np.random.randn(3)

array([-0.21143412,  0.47651969,  0.07865118])

In [30]:
arr = np.random.randint(5,60,(4,4))

In [31]:
arr.reshape(8,-23323)

array([[12, 30],
       [11, 55],
       [11, 45],
       [53, 29],
       [ 5, 36],
       [56, 55],
       [32, 12],
       [59, 16]])

In [32]:
arr.max()

59

In [33]:
arr.min()

5

In [34]:
arr[2:,2:]

array([[56, 55],
       [59, 16]])

In [35]:
arr

array([[12, 30, 11, 55],
       [11, 45, 53, 29],
       [ 5, 36, 56, 55],
       [32, 12, 59, 16]])

In [36]:
arr[:,[1,3]]

array([[30, 55],
       [45, 29],
       [36, 55],
       [12, 16]])

In [38]:
arr[arr>10]

array([12, 30, 11, 55, 11, 45, 53, 29, 36, 56, 55, 32, 12, 59, 16])

In [40]:
arr*arr #scaler multiplication

array([[ 144,  900,  121, 3025],
       [ 121, 2025, 2809,  841],
       [  25, 1296, 3136, 3025],
       [1024,  144, 3481,  256]])

In [42]:
arr@arr #matrix mutiplication

array([[2289, 2766, 5583, 3015],
       [1820, 4611, 7185, 5289],
       [2496, 4446, 8344, 5279],
       [1323, 3816, 5236, 5609]])

In [43]:
arr**2

array([[ 144,  900,  121, 3025],
       [ 121, 2025, 2809,  841],
       [  25, 1296, 3136, 3025],
       [1024,  144, 3481,  256]])

In [44]:
arr

array([[12, 30, 11, 55],
       [11, 45, 53, 29],
       [ 5, 36, 56, 55],
       [32, 12, 59, 16]])

In [45]:
np.sqrt(arr)

array([[3.46410162, 5.47722558, 3.31662479, 7.41619849],
       [3.31662479, 6.70820393, 7.28010989, 5.38516481],
       [2.23606798, 6.        , 7.48331477, 7.41619849],
       [5.65685425, 3.46410162, 7.68114575, 4.        ]])

In [46]:
np.exp(arr)

array([[1.62754791e+05, 1.06864746e+13, 5.98741417e+04, 7.69478527e+23],
       [5.98741417e+04, 3.49342711e+19, 1.04137594e+23, 3.93133430e+12],
       [1.48413159e+02, 4.31123155e+15, 2.09165950e+24, 7.69478527e+23],
       [7.89629602e+13, 1.62754791e+05, 4.20121040e+25, 8.88611052e+06]])

In [47]:
np.log10(arr)

array([[1.07918125, 1.47712125, 1.04139269, 1.74036269],
       [1.04139269, 1.65321251, 1.72427587, 1.462398  ],
       [0.69897   , 1.5563025 , 1.74818803, 1.74036269],
       [1.50514998, 1.07918125, 1.77085201, 1.20411998]])

In [49]:
np.random.seed(30)
np.random.rand(2,4)

array([[0.64414354, 0.38074849, 0.66304791, 0.16365073],
       [0.96260781, 0.34666184, 0.99175099, 0.2350579 ]])